version: "2.3"
# Stick to an older version of the docker-compose.yml format to ensure we can use
# the GPU even with older versions of docker-compose, with 'runtime: nvidia'
# (see https://docs.docker.com/compose/gpu-support/#use-of-service-runtime-property-from-compose-v23-format-legacy)

services:
  backend:
    build:
      context: ../..
      dockerfile: ui/prod-env/backend/Dockerfile
    env_file:
      - secrets.env
    environment:
      PPL_DATABASE_URL: "sqlite+pysqlite:///data/ppl.db"
    volumes:
      - backend-data:/application/data
    runtime: nvidia
    restart: always  # Handle reboots of the host machine
  frontend-and-fanout:
    build:
      context: ../..
      dockerfile: ui/prod-env/frontend-and-fanout/Dockerfile
    ports:
      - ${PPL_FANOUT_PORT}:80
    depends_on:
      - backend
    restart: always
volumes:
  backend-data:
